### ISSUE TITLE
Change Sertain Image in Body.

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Brinks-Safe-Site#10]
Please change the next image to the new design.
New design ready in drive.
![image](https://user-images.githubusercontent.com/26923359/28569842-3d05dca6-7144-11e7-8de2-25d91f0372c0.png)

**Comment by MeanEYE** [comment]
You mean the logo?

**Comment by talovdat** [comment]
I mean that this gray strip that I marked have a new design that needs to be upload.

**Comment by MeanEYE** [comment]
What you marked is not an image and more to the point you said "sertain" which I assume means "certain" implying a specific image that needs to be changed. Hence my question.

**Comment by MeanEYE** [comment]
Am closing this due to both of you sucking and not knowing what the hell you want. Phrase the issue properly, explain what needs to me done and then we do. This color, background, image that's not image and similar is not going to work.
