### ISSUE TITLE
Text in header.

### ISSUE THREAD

**Issue by VladimirWebDev** [Way2CU/Brinks-Safe-Site#13]
![image](https://user-images.githubusercontent.com/25882157/28577963-8e7a957c-7158-11e7-9313-ada78252af60.png)
Can you check added text in header. I just copied for test purpose and don't now is it regular.
Left space in phone number for 13 digits..

**Comment by talovdat** [comment]
@VladimirWebDev Are you asking if that's how the header text should go?
 If that is so, then yes.

**Comment by VladimirWebDev** [comment]
Sorry for late response, had issue with internet.. Yes that was the question.. Ok, than it's correct.

**Comment by MeanEYE** [comment]
@talovdat close it in future.
