### ISSUE TITLE
Phone number alignment

### ISSUE THREAD

**Issue by eyalway2cu** [Way2CU/Brinks-Safe-Site#5]
Phone numbers are RTL instead of LTR. Not only that, they also need to be written with the star sign on the left side.

![image](https://user-images.githubusercontent.com/7808985/28018821-5c2f209c-6587-11e7-85b5-bf1947d9fb79.png)

**Comment by MeanEYE** [comment]
@VladimirWebDev just modify CSS to have `direction: ltr;` on phone class always.

**Comment by eyalway2cu** [comment]
very important, the constant needs to change as well so it shows as *5667 and not 5667*.

**Comment by eyalway2cu** [comment]
star sign got ommited, in case I wasnt clear starsign5667 instead of 5667starsign.

**Comment by VladimirWebDev** [comment]
*5667 ?

**Comment by MeanEYE** [comment]
Yes, @VladimirWebDev phone number format is `*5667`. Just @eyalway2cu sucks at writing :) Markdown. Just check if language constant has the star in front of numbers, not at the back.
