### ISSUE TITLE
Phone number padding issue

### ISSUE THREAD

**Issue by eyalway2cu** [Way2CU/Brinks-Safe-Site#7]
Padding right on top phone element does not work well when using Callbox, the number will get swapped by a tracking number but because of its padding right attribute it gets pushed down.
![image](https://user-images.githubusercontent.com/7808985/28022296-724e76c8-6593-11e7-9782-fae40b3dfc07.png)

**Comment by MeanEYE** [comment]
What does it get swapped with?

**Comment by eyalway2cu** [comment]
I would like to use Callbox here, the number will get swapped to a 7 digit number.

**Comment by VladimirWebDev** [comment]
@eyalway2cu  Is there a chance for this number to go bigger, 8,9 digits..?

**Comment by eyalway2cu** [comment]
maximum 11 Characters.
possible formats (just to demonstrate):
09-9999999
09-999-9999

**Comment by VladimirWebDev** [comment]
Ok.. cause my solution fixes problem with 7 digits so i thought to set width on element giving you enough space if number gets bigger and than fix padding. Should I do it..?

**Comment by eyalway2cu** [comment]
Whatever would make this work works for me :).

**Comment by VladimirWebDev** [comment]
Example..
![image](https://user-images.githubusercontent.com/25882157/28066759-8112cece-663e-11e7-8dc6-368ebf9b0ba4.png)

**Comment by eyalway2cu** [comment]
thats perfect
